version: "3"

services:
  hugo-andrea-app5:
    # A hugo static web site
    image: arpasali/hugo-alai-idrometri:0.0.1
    labels:
      - "traefik.http.routers.app5.rule=Host(`app5.wdipgeo.arpas.adds`)"
networks:
  default:
    external: true
    name: traefik72_default
      